server:
  port: ${random.int[6000,7000]}

spring:
  application:
    name: consul-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${random.value}
#        serviceName: myservice-myprefix-${spring.application.name}